# Generated by Django 5.2.9 on 2025-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_alter_directory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='encryption_key',
            field=models.BinaryField(default=b'', help_text='Ключ шифрования файла, зашифрованный мастер-ключом сервера.', max_length=255),
            preserve_default=False,
        ),
    ]
