# Generated by Django 5.2.9 on 2025-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_userfile_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Общий доступ'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ссылки'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Токен доступа'),
        ),
    ]
